name: star_battle
description: An implementation of the Star Battle game.
version: 1.0.0
repository: https://github.com/mateusfccp/star_battle/packages/start_battle

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  collection: ^1.19.0
  meta: ^1.15.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
