name: star_battle_app
description: "An app that provides a UI for the Star Battle game."
publish_to: 'none'
version: 1.0.0
repository: https://github.com/mateusfccp/star_battle/packages/start_battle_app

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  star_battle: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
